name: Netlify TrafficServer
on:
  push:
    branches:
      - 7.1.x-netlify
      - 9.0.x-netlify
  pull_request:
    branches:
      - 7.1.x-netlify
      - 9.0.x-netlify
jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: true
      matrix:
        build-type: [Debug, Release]
        include:
          - build-type: Debug
            AM_CXXFLAGS: "-Og -ggdb -fno-omit-frame-pointer"
            CONFIGURE_OPTS: "--enable-asan --enable-debug"
            LSAN_OPTIONS: "detect_leaks=0"
          - build-type: Release
            AM_CXXFLAGS: "-O2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Build Environment
        run: |
          sudo apt update && sudo apt -y upgrade
          sudo apt install -y build-essential autoconf automake libtool pkg-config
          sudo apt install -y software-properties-common ca-certificates apt-transport-https curl wget
          sudo apt install -y lsb-release lz4 zstd
          sudo apt install g++-9 gcc-9
      - name: Install Dependencies
        run: >
          sudo apt install -y
          libluajit-5.1-dev
          libunwind8-dev
          libexpat1-dev
          libhwloc-dev
          libgeoip-dev
          libpcre3-dev
          libyamlcpp-dev
          liblzma-dev 
          libcap-dev
          libssl-dev
          libb64-dev
          zlib1g-dev
          tcl-dev
      - name: Generate Configure Script
        run: autoreconf --install --force
      - name: Create Build Directory
        run: mkdir -p ${{ github.workspace }}/build
      - name: Configure
        run: ${{ github.workspace }}/configure --prefix=/opt/ts --enable-experimental-plugins
        working-directory: ${{ github.workspace }}/build
        env:
          AM_CXXFLAGS: "${{ matrix.AM_CXXFLAGS }} -std=c++17 -Wno-cpp -Wno-deprecated-copy"
          CONFIGURE_OPTS: ${{ matrix.CONFIGURE_OPTS }}
      - name: Build TrafficServer
        run: make -j
        env:
          LSAN_OPTIONS: ${{ matrix.LSAN_OPTIONS }}
      - name: Package
        if: github.event_name == "push"
        run: echo TODO
