---
name: Rebase onto upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

  repository_dispatch:
    types:
      - "on-demand-check"

jobs:
  update-branches:
    name: "update branches from upstream"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { local: master, upstream: master }
          - { local: master-netlify, upstream: master }
          - { local: "9.1.x", upstream: "9.1.x" }
          - { local: "9.1.x-netlify", upstream: "9.1.x" }
          - { local: "9.2.x", upstream: "9.2.x" }
          - { local: "9.2.x-netlify", upstream: "9.2.x" }
    steps:
      - uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}
      - name: clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: rebase upstream
        uses: zxaos/patchup@v1
        with:
          local_branch: ${{ matrix.local }}
          github_token: ${{ steps.get-token.outputs.token }}
          upstream_branch: ${{ matrix.upstream }}
          upstream_repo: apache/trafficserver
          target_tag: patchup-${{ matrix.local }}
          conflict_reviewers: "@netlify/core-pod-adn"
